### ISSUE TITLE
Matchmaker issues 

### ISSUE THREAD

**Issue by anniepham7** [volkamerlab/superposer#17]
- [ ] We need to deal with the whole structure (residues atoms do not have the same length)

- [ ] get more information of mda_align.alignto() / Does MDA move the structure as part of the RMSD calculation?

- [ ] get superposed atomium model(s)

**Comment by jaimergp** [comment]
> get more information of mda_align.alignto() / Does MDA move the structure as part of the RMSD calculation?

`mobile` is transformed as part of the aligner, as per the [docs here](https://www.mdanalysis.org/docs/documentation_pages/analysis/align.html?highlight=superposition#MDAnalysis.analysis.align.alignto).

While looking up the docs, I realized MDAnalysis already provides helpers for sequence alignment! Read [here](https://www.mdanalysis.org/docs/documentation_pages/analysis/align.html?highlight=superposition#common-usage). This mentions you can use [`fasta2select`](https://www.mdanalysis.org/docs/documentation_pages/analysis/align.html?highlight=superposition#MDAnalysis.analysis.align.fasta2select) to detect the residue pairing automatically (you can even run the alignment there instead of using biotite!) and then feed the resulting dictionary to the [`AlignTraj`](https://www.mdanalysis.org/docs/documentation_pages/analysis/align.html?highlight=superposition#MDAnalysis.analysis.align.AlignTraj) class. Let's see if this solves some of our problems and, if that's the case, we will backport some of the `fasta2select` code into our routines.
